DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS candidates;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS pgcrypto;
