DELETE FROM sessions WHERE user_id IN (SELECT id FROM users WHERE username IN ('owner', 'gateway'));
DELETE FROM users WHERE username IN ('owner', 'gateway');

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM api;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM api;
REVOKE USAGE ON SCHEMA public FROM api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM api;
DROP ROLE IF EXISTS api;
